#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
#
[[layers]]
  name = "colorscheme"

[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    bootstrap_before = "myspacevim#before"
    autocomplete_method = "deoplete"
    default_indent = 4
    expand_tab = false
	
	# options for statusline
    # Set the statusline separators of statusline, default is "arrow"
    statusline_separator = "arrow"

    # Set the statusline seperators of inactive statusline
    statusline_inactive_separator = "arrow"

	# Enable status line mode
	enable_statusline_mode = true

    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

	# left sections of statusline
    statusline_left_sections = [
		'winnr'
       'filename'
    ]

	 # right sections of statusline
    statusline_right_sections = [
       'fileformat',
	   'percentage',
       'cursorpos',
       'input method'
    ]



# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

name = "tmux"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#python"
  python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]
